### ISSUE TITLE
VistaPool  blocked from loading

### ISSUE THREAD

**Issue by ppenders** [tellerbop/havistapool#10] opened 2021-06-04 14:24 UTC
Hi,

As of the latest version of core the integration is now blocked from loading, see details in the logging:

2021-06-04 14:21:31 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'vistapool' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details.

Any change you could fix this?

Thank You!

Perry

**Comment by olafvs** [comment] 2021-06-10 07:26
The integration is not working at the moment and is being worked on: [https://github.com/tellerbop/havistapool/issues/9](https://github.com/tellerbop/havistapool/issues/9)

**Comment by tellerbop** [comment] 2021-06-10 08:06
This will be fixed as soon as #9 is fixed

**Comment by tellerbop** [comment] 2021-06-10 08:07
duplicate of #7

**Closed as completed by tellerbop** 2021-06-10 08:07 UTC
